### PR TITLE
Upgrade kernel

### PR DESCRIPTION
**Pull request by infinitebash**
Updated kernel to v6.7-rc and updated the mt8183 and x86 configs using make oldconfig. I confirmed the x86 config was able to boot both into a shell and into Ultramarine Linux. I need someone to confirm the new mt8183 config works.

### CODE REVIEW

**Review by ellyq — COMMENTED** [review]
Hi!
Are there any benefits of updating the kernel for x86?

Staying with LTS for bootloader is desirable in my opinion, as it won't require as much maintenance and we don't need new features from upstream.

The only reason why we used 6.7-rc* for MT8183 was that it was the source I had "on hand", as pulling new tree takes a lot of data and time with 4G connection (which currently is my main uplink).

We're trying to stay as close to mainline as possible with kernels used in distributions, as we upstream code and need to test for any regressions. I don't think it's necessary in this case though :)

**Comment by WeirdTreeThing** [comment]
>Staying with LTS for bootloader is desirable in my opinion, as it won't require as much maintenance and we don't need new features from upstream.

Not like x86 was on a LTS release at all.

**Comment by infinitebash** [comment]
I agree, an LTS kernel makes more sense. I've replaced the one kernel submodule with two (one mainline and one LTS) and modified the Makefile to use the LTS kernel for x86 and the mainline kernel for arm. Also put the v6.6.3 x86 config (from main) back and retested it (it worked). I believe the arm config still needs to be updated.

**Review by ellyq — COMMENTED** [review]
Friend of mine just tested build from this tree, framebuffer is broken.
Will do more testing/fixups once I'll get back home on Friday (Jan 5th) :)

**Pull request closed without merging**
